In [1]:
import numpy as np

numpy는 내부적으로 c로 구현 되어있다. 수치에 관련된 프로그래밍을 할 때 일반 python보다 훨씬 빠르다.
특히, 배열 연산에 특화 되어있다.

# np.array

In [4]:
# 일반 파이썬 리스트를 numpy 배열화(numpy 배열 : ndarray)

py_list = [1,2,3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [5]:
# ndarray 타입 확인해보기

type(arr1)

numpy.ndarray

In [6]:
py_list=[[1,2,3],[4,5,6]]
arr2 = np.array(py_list)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

# np.arrange

In [8]:
arr = np.arange(10) # 0-9까지 들어있는 숫자 배열을 생성
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

# np.zeros
 - 지정한 차원에 모든 원소를 0으로 채운다

In [12]:
np.zeros(5) # 1차원 배열에 5개의 0을 채운다

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3)) # 2행 3열 (2차웝 배열)의 배열에 0을 채운다

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# np.ones
- 지정한 차원에 모든 원소를 1로 채운다.


In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# np.full
- 지정한 차원에 모든 원소를 원하는 수로 채운다.

In [19]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

# np.eye
- 단위행렬

In [22]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# np.linspace
- 구간나구기

In [25]:
np.linspace(1,10,3) # 1부터 10까지 2개의 구간 만들기

array([ 1. ,  5.5, 10. ])

In [26]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

# Random을 사용하기 위한 numpy
- 보통 랜덤한 배열은 딥러닝에서 매개변수의 초기화를 하기 위해 사용
- 딥러닝에서는 일반적으로 Xavier 초기값, He 초기값, 정규분포 초기값을 계산해 준다.

## np.random.rand
- 완전한 랜덤 만들기 (정규분포나 균등분포가 아닌 랜덤값)

In [27]:
np.random.rand(2,3)

array([[0.88156637, 0.90126228, 0.28643923],
       [0.07072475, 0.32419847, 0.22326288]])

## np.random.randn
- 정규분포 랜덤값 만들기

In [29]:
np.random.randn(10)

array([-0.68176816,  0.00186409, -0.9884973 , -1.46773906,  0.45654293,
        0.1548714 , -0.27277244,  0.62289724,  0.19379687, -0.68434758])

## np.random.uniform
- 균등분포 랜덤값 만들기

In [30]:
np.random.uniform(1,3,size=(4,5))

array([[1.30052837, 2.52747992, 1.22853928, 1.70947973, 2.94241991],
       [1.45138863, 2.11753365, 2.1084359 , 2.4811383 , 2.04651976],
       [1.81653427, 1.74207558, 2.36461837, 1.52909393, 2.39799926],
       [1.4627356 , 1.15010705, 1.06102941, 2.5043392 , 1.28058783]])

## np.random.randint
- 정수 랜덤 만들기

In [32]:
np.random.randint(1,100,size=(5,)) 
# 1차원 배열의 원소 5개에 1 ~ 100까지의 랜덤값으로 채우기

array([84, 95, 94,  8, 41])

In [33]:
np.random.randint(1,100,size=(2,3)) 

array([[11, 76, 98],
       [97, 60, 83]])

## np.random.choice
- 정수 랜덤 샘플링하기
- 랜덤 샘플링 : 일정한 범위 내에서 필요한 정수를 랜덤으로 추출
- 미니배치를 만들 때 사용합니다.

In [36]:
np.random.choice(100,size=(3,4))

array([[56, 95, 39, 18],
       [52, 60, 49, 54],
       [98, 32, 59,  3]])

In [38]:
# 임의의 배열을 만들어서 그 안에서 랜덤하게 추출할 수 있도록 함.
arr = np.arange(1,6)
np.random.choice(arr,size=(2,2),replace=False) # replace가 true이면 원소를 중복 추출, False이면 중복 추출 x

array([[5, 4],
       [1, 3]])

# 인덱스와 슬라이싱

In [41]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr[0][2]

3

In [44]:
arr[0,2]

3

In [46]:
arr[:,2]

array([3, 8])

In [47]:
arr = np.arange(1,37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [50]:
arr[:,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[13, 14],
        [16, 17]],

       [[25, 26],
        [28, 29]]])

In [51]:
arr[1:,1:3,1:]

array([[[17, 18],
        [20, 21]],

       [[29, 30],
        [32, 33]]])

# 배열의 차원과 형상
- 형상(shape)
- 차원수(ndim)


In [53]:
arr= np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
arr.shape

(3, 4)

In [55]:
arr.ndim

2

## 차원수 확장하기
- 항상 같은 예시는 아니지만, 보통은 이미지분석(CNN)을 하기 위해 데이터를 전처리 하면서 사용된다.
- tensorflow는 tf.newaxis를 활용, numpy는 np.newaxis를 활용해서 추가 차원을 만들어 낼 수 있다.

In [56]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
tnp_arr = arr[np.newaxis,:,:,np.newaxis]
tnp_arr

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

In [58]:
# 실제 데이터를 다룰 때는 실제 데이터를 보는 것이 아닌,shape만 보자...
tnp_arr.shape

(1, 3, 4, 1)

In [59]:
# 각 차원이 1인 차원 삭제하기
tnp_arr2 = np.squeeze(tnp_arr)
tnp_arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## spread 연산자 활용하기
- 슬라이싱 도중에 특정 차원 부터는 전체를 선택할 때 사용한다.

In [61]:
tnp_arr3 = arr[np.newaxis, ...,np.newaxis]
tnp_arr3.shape

(1, 3, 4, 1)

## 배열의 형상 (shape) 바꾸기
- np.newaxis 를 활용해서 축을 추가한다.(차원수를 늘린다)


평탄화
- 'ravel' : 원본 배열을 평탄화 시킨 참조배열을 만들어 낸다.
- 'flatten' : 평탄화 시킨 복사된 배열을 만들어 낸다.

형상변환 
- reshape

In [62]:
x = np.arange(15).reshape(3,5)
x.shape

(3, 5)

In [64]:
print('원본 x : \n{}'.format(x))

원본 x : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [65]:
temp = np.ravel(x)
print('ravel로 평탄화된 x : \n{}'.format(temp))

ravel로 평탄화된 x : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [67]:
temp[0] = 100

In [68]:
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [73]:
# flatten은 평탄화 하면서 복사본을 만들어 낸다.
y = np.arange(15).reshape(3,5)
temp2 = y.flatten()
print('원본 y : \n{}'.format(y))
print('flatten으로 평탄화된 y의 shape : {}'.format(temp2.shape))
print('flatten으로 평탄화된 y : \n{}'.format(temp2))

원본 y : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
flatten으로 평탄화된 y의 shape : (15,)
flatten으로 평탄화된 y : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [74]:
temp2[0] = 100
print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


reshape 사용하기
- 함수 내의 모든 숫자를 곱했을때 스칼라 원소의 개수와 같기만 하면 된다

In [75]:
x  = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
x.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [77]:
x.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
x.reshape(2,2,-1) # 2*2는 4니까 -1은 5를 의미하게 된다.

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

# 브로드캐스팅

In [82]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
x*2
# x는 2차원, 2는 0차원 스칼라 값이다. 2의 차원이 곱해지는 배열인 x의 shape으로 확장된다.

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [91]:
# shape이 다를 때의 연산
a = np.arange(12).reshape(4,3) #(4,3)
b = np.arange(100,103) # (3,)
c = np.arange(1000,1004) # (4,)
d = b.reshape(1,3) # (1,3)

In [92]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
b

array([100, 101, 102])

In [94]:
a*b

array([[   0,  101,  204],
       [ 300,  404,  510],
       [ 600,  707,  816],
       [ 900, 1010, 1122]])

In [97]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

# 전치행렬 만들기
- 행렬 A의 행과 열의 인덱스를 바꾼 것을 전치행렬이라고 한다.
- $A{(i,j)}$의 위치를 $A{(j,i)}$로 바꾼 것

In [98]:
e = np.arange(6).reshape(2,3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
e.T

array([[0, 3],
       [1, 4],
       [2, 5]])