<a href="https://colab.research.google.com/github/jang3463/machinelearning-deeplearning-lecture/blob/main/Tensorflow_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor란?

Tensor : 배열

* 배열인데 Rank 시스템이 있음
* 0 Rank Tensor - Scalar - 상수
* 1 Rank Tensor - Array (Vector)  - 1차원 배열
* 2 Rank Tensor - Matrix - 행렬
* 3 Rank Tensor - Tensor - 3차원 배열
* 4 Rank Tensor - Tensor - 4차원 배열 ...

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 각종 시쿼스들을 tensor로 변환이 가능

# 1. list -> tensor 
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [3]:
# 2. tuple -> tensor
tf.constant((1,2,3,))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
# 3. ndarray -> tensor

arr = np.array([1,2,3])
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

# Tensor 정보 확인하기

In [5]:
tensor = tf.constant(arr)
tensor.shape

TensorShape([3])

In [6]:
tensor = tf.constant(np.arange(0,10).reshape(2,5))
tensor.shape

TensorShape([2, 5])

In [7]:
tensor.dtype

tf.int64

In [8]:
# 텐서를 구성하는 원소 중 데이터 타입이 가장 큰 것이 텐서의 데이터 타입이 된다.
# 텐서에 정수와 실수가 섞여 있으면 텐서의 타입은 실수가 된다.

tensor = tf.constant([1,2.1,3])
tensor.dtype

tf.float32

In [10]:
# 강제로 데이터 타입을 지정
tensor = tf.constant([1,2,3], dtype=tf.float32)
tensor.dtype

tf.float32

In [12]:
# tf.cast 를 활용해서 텐서의 타입을 변경 
tf.cast(tensor, tf.uint8).dtype

tf.uint8

In [14]:
# numpy와 tensorflow는 상호간에 호환이 가능

# 1. tensor를 ndarray로 바꿔보기
tensor.numpy()

array([1., 2., 3.], dtype=float32)

# Tensorflow의 난수 생성

In [15]:
#numpy로 정규분포 만들기

np.random.randn(9)

array([-0.72700972, -0.2170077 , -0.17906021, -0.28135279,  0.39404005,
       -1.46697714, -0.75770611, -0.70878729, -0.08070901])

In [16]:
# tensorflow로 정규분포 만들기
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3866811 , -2.3282123 ,  1.4526869 ],
       [ 1.1507498 , -0.69778824, -2.2397685 ],
       [ 1.6902353 ,  0.6275519 ,  0.2099564 ]], dtype=float32)>

In [17]:
# tensorflow로 균등분포 만들기
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.43406403, 0.5329131 , 0.7452849 ],
       [0.37855208, 0.09035909, 0.69804096],
       [0.3726461 , 0.22268915, 0.62960696]], dtype=float32)>

# Tensorflow 로 One Hot Encoding

In [18]:
from tensorflow.keras.utils import to_categorical

In [19]:
to_categorical(1,3)

array([0., 1., 0.], dtype=float32)